#If a player does not join with CheatBreaker, kick them?
kick: true

#Kick Player after x many ticks // 20 ticks = 1 second
kick-delay: 20

#Messages
server-restart: "Everyone has been kicked for re-authentication."
recommendation-message: "&fUsing &c&lCheat&f&lBreaker &fis highly recommended. You may download the client at &chttps://cheatbreaker.com&f."
kick-message: "&cPlease use CheatBreaker to join the server! Download at cheatbreaker.com!"
welcome-message: "&aThank you for using CheatBreaker!"
no-permission: "&cNo permission."
could-not-find-player: "&cCould not find player."
player-is-on-cheatbreaker: "&a%player% is using CheatBreaker!"
player-is-not-on-cheatbreaker: "&c%player% is not using CheatBreaker!"